### ISSUE TITLE
How to create alerts sensor

### ISSUE THREAD

**Issue by dnestico** [Arroma98/Pixel-like-dashboard#3]
This is gonna sound like a question for noobs but just wondering how did you create your alerts_on sensor? So I can implement it too with the card you made. Thanks

**Comment by Arroma98** [comment]
configuration.yaml

```
sensor:
  - platform: template
    sensors:
         alarms:
           friendly_name: Alarms
           unit_of_measurement: ''
           value_template: >
             {% set alarms = [
               states.entity1,
               states.entity2,
               states.entity3,
               ] %}
             {{ alarms | selectattr('state','eq','on') | list | count }}
```

states.entity written as `states.light.living_room` or `states.input_boolean.water_flow `or `states.binary_sensor.entry_door`, ...

**Comment by Arroma98** [comment]
Added `counter_sensor_example.yaml`

**Comment by dnestico** [comment]
Thanks!

**Comment by dnestico** [comment]
Ok so I'm making this now and I already have a sensor that counts the lights, switches, and other devices that are on. How did you combine it in to the one alerts_on sensor?

**Comment by Arroma98** [comment]
You create another counter sensor that encloses all those entities you want, as I showed you above.
Or if you already have a light counter, a climate counter, etc. and you want everything to come out in the alerts, you can create a sensor that is the sum of these counters.

**Comment by Arroma98** [comment]
Like 
```
  - platform: template
    sensors:
        alerts_on:
          friendly_name: "Alerts on"
          unit_of_measurement: ''
          value_template: "{{ float(states('sensor.lights_on')) + float(states('sensor.climate_on')) }}"
```
Or you create one with all the entities you want to see as alerts, just like you did the one for the lights (I imagine), only with the entities to put in the alerts.
And you use the code I wrote the other day.

**Comment by dnestico** [comment]
Getting an error now unfortunately when trying to restart, can't you tell me whats wrong with my code? Thanks.

<img width="619" alt="Screenshot 2023-06-25 at 8 33 44 PM" src="https://github.com/Arroma98/Pixel-like-dashboard/assets/3034555/c70d3ecd-d4c3-40a7-acdb-3c5cf1435c1b">

```
(sensor.yaml)

# Alerts on sensor
- platform: template
  sensors:
      alerts_on:
        friendly_name: "Alerts on"
        unit_of_measurement: ''
        value_template: "{{ float(states('sensor.current_lights_on')) + float(states('sensor.climate_on')) }}"

# Climate alert sensor
- platform: template
  sensors:
      climate_on:
        friendly_name: "Climate on"
        unit_of_measurement: ''
        value_template: >
          {% set climate = [
            states.climate.3family_room,
            ] %}
          {{ climate | selectattr('state','eq','heat') | list | count + climate | selectattr('state','eq','cool') | list | count + climate | selectattr('state','eq','dry') | list | count + climate | selectattr('state','eq','fan_only') | list | count }}
```

**Comment by Arroma98** [comment]
Bad brackets often disturb, but in the alerts code everything seems ok to me.
Even the climate code seems well written to me.
Did you put "sensor" above everything?

```
sensor:

# Alerts on sensor
- platform: template
  sensors:
      alerts_on:
        friendly_name: "Alerts on"
        unit_of_measurement: ''
        value_template: "{{ float(states('sensor.current_lights_on')) + float(states('sensor.climate_on')) }}"

# Climate alert sensor
- platform: template
  sensors:
      climate_on:
        friendly_name: "Climate on"
        unit_of_measurement: ''
        value_template: >
          {% set climate = [
            states.climate.3family_room,
            ] %}
          {{ climate | selectattr('state','eq','heat') | list | count + climate | selectattr('state','eq','cool') | list | count + climate | selectattr('state','eq','dry') | list | count + climate | selectattr('state','eq','fan_only') | list | count }}
```

**Comment by dnestico** [comment]
Im not sure why that still isn't working, I have a sensors.yaml file so I normally don't need to put "sensor" above everything like all my other sensors. Idk what's wrong but it clearly doesn't like the climate alert sensor. So weird and annoying.

In sensor.yaml:

```
# Alerts on sensor
- platform: template
  sensors:
    alerts_on:
      friendly_name: "Alerts on"
      unit_of_measurement: ''
      value_template: "{{ float(states('sensor.current_lights_on')) + float(states('sensor.climate_on')) }}"

# Climate alert sensor
- platform: template
  sensors:
    climate_on:
      friendly_name: "Climate on"
      unit_of_measurement: ''
      value_template: >
        {% set climate = [
          states.climate.3family_room,
          ] %}
        {{ climate | selectattr('state','eq','heat') | list | count + climate | selectattr('state','eq','cool') | list | count + climate | selectattr('state','eq','dry') | list | count + climate | selectattr('state','eq','fan_only') | list | count }}
```

**Comment by dnestico** [comment]
After removing the climate alert sensor, it started working, I guess my code is messed up on that sensor... 
<img width="499" alt="Screenshot 2023-06-26 at 3 44 52 PM" src="https://github.com/Arroma98/Pixel-like-dashboard/assets/3034555/ba4f2cd6-4f83-444a-9850-c45091ea10b5">

**Comment by dnestico** [comment]
After removing the climate alert sensor, it started working, I guess my code is messed up on that sensor... 

<img width="498" alt="Screenshot 2023-06-26 at 3 55 42 PM" src="https://github.com/Arroma98/Pixel-like-dashboard/assets/3034555/f426ccb6-1308-4a85-9237-a4467b9783c1">

Not sure why the state is 0.0 though instead of just 0 so changed that in the card and works, need to get the other sensor fixed now

<img width="507" alt="Screenshot 2023-06-26 at 3 57 02 PM" src="https://github.com/Arroma98/Pixel-like-dashboard/assets/3034555/a4b1d9f0-f5f0-4d68-b473-033a986f1a8e">

**Comment by dnestico** [comment]
Sorry for re-opening this issue, I have a climate group that tells me if the thermostat is on or off but its basically useless because it always reports as on meaning the notification would always be there, so hope there's a way we can fix the climate sensor above...

Meanwhile here a sensor that tracks when lock is unlocked and it works perfectly fine, weird... 

```
# Locks active sensor
- platform: template
  sensors:
    locks_unlocked:
      value_template: >
        {% set locks = [
          states.lock.front_door,
          ] %}
        {{ locks | selectattr('state','eq','unlocked') | list | count }}
```

**Comment by Arroma98** [comment]
To remove the decimal value use |round(0).

```
# Alerts on sensor
- platform: template
  sensors:
    alerts_on:
      friendly_name: "Alerts on"
      unit_of_measurement: ''
      value_template: "{{ (float(states('sensor.current_lights_on')) + float(states('sensor.climate_on')))|round(0) }}"
```

I can't figure out what's wrong with the climate code, below I've pasted the code I'm currently using which includes both air conditioners and thermostats:

```
sensor:
  - platform: template
    sensors:
         clima_accesi:
           friendly_name: Clima accesi
           unit_of_measurement: ''
           value_template: >
             {% set climate = [
               states.climate.thermostat_23,
               states.climate.thermostat_25,
               states.climate.thermostat_27,
               states.climate.termostato_camera_m,
               states.climate.termostato_camera_armadi,
               states.climate.termostato_soggiorno,
               states.climate.mitsubishi_levante,
               states.climate.mitsubishi_ponente,
               ] %}
             {{ climate | selectattr('state','eq','heat') | list | count + climate | selectattr('state','eq','cool') | list | count + climate | selectattr('state','eq','dry') | list | count + climate | selectattr('state','eq','fan_only') | list | count }}
```

**Comment by Arroma98** [comment]
At this point try to put it directly in the configuration.yaml under `sensor:`
If that doesn't work then the issue needs to be investigated

**Comment by dnestico** [comment]
Tried this in configuration.yaml and its still throwing and error with the template for whatever reason, I will ask on the forums or github if someone knows why soon probably at this point, thanks. 

Update: I asked on the forums... https://community.home-assistant.io/t/climate-alert-sensor-wont-work/586221?u=davidnestico

```
sensor:
  - platform: template
    sensors:
         climate_on:
           friendly_name: "Climate on"
           unit_of_measurement: ''
           value_template: >-
             {% set climate = [
               states.climate.3family_room,
               ] %}
             {{ climate | selectattr('state','eq','heat') | list | count + climate | selectattr('state','eq','cool') | list | count + climate | selectattr('state','eq','dry') | list | count + climate | selectattr('state','eq','fan_only') | list | count }}
```

Side note... I added the round(0) thing and it still reports as 1.0, weird, maybe there's a newer way with the latest update to do it differently...

```
# ALERTS ON sensor
- platform: template
  sensors:
    alerts_on:
      friendly_name: "Alerts on"
      unit_of_measurement: ''
      value_template: "{{ float(states('sensor.current_lights_on')) + float(states('sensor.locks_unlocked')) + float(states('sensor.media_players_active'))|round(0) }}"
```

**Comment by dnestico** [comment]
So according to the forums its because I am putting only one thermostat in a list which wouldn't work unless there are multiple, so I need to "Use the new template" apparently which I gotta find out how soon...

**Comment by Arroma98** [comment]
I had a doubt that it was for the single element in the list, but then you had the 'locks' sensor that worked even though it also had only one element so I discarded that idea.

When you solve with this new template, can you put it here?
I wasn't aware of it

**Comment by dnestico** [comment]
Will do, currently tryna follow this to get it working.... https://www.home-assistant.io/integrations/template/

btw do you get any errors with your counter sensors? Like the other ones are working fine but just noticed there's some errors in the log, so that's weird...

Another thing btw, something must've changed with the newer updates because the "round 0) thing ain't working for me and it still reporting "1.0" instead of just 1... 

```
# ALERTS ON sensor
- platform: template
  sensors:
    alerts_on:
      friendly_name: "Alerts on"
      unit_of_measurement: ''
      value_template: "{{ float(states('sensor.current_lights_on')) + float(states('sensor.locks_unlocked')) + float(states('sensor.media_players_active'))|round(0) }}"
```

```
Logger: homeassistant.helpers.template_entity
Source: helpers/template_entity.py:380
First occurred: 3:43:05 PM (1 occurrences)
Last logged: 3:43:05 PM

TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ float(states('sensor.current_lights_on')) + float(states('sensor.locks_unlocked')) + float(states('sensor.media_players_active'))|round(0) }}' but no default was specified') while processing template 'Template<template=({{ float(states('sensor.current_lights_on')) + float(states('sensor.locks_unlocked')) + float(states('sensor.media_players_active'))|round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.alerts_on'
```

```
Logger: homeassistant.helpers.event
Source: helpers/template.py:565
First occurred: 3:43:05 PM (1 occurrences)
Last logged: 3:43:05 PM

Error while processing template: Template<template=({{ float(states('sensor.current_lights_on')) + float(states('sensor.locks_unlocked')) + float(states('sensor.media_players_active'))|round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1898, in forgiving_float
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 563, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2179, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1901, in forgiving_float
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1609, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ float(states('sensor.current_lights_on')) + float(states('sensor.locks_unlocked')) + float(states('sensor.media_players_active'))|round(0) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 684, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 565, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ float(states('sensor.current_lights_on')) + float(states('sensor.locks_unlocked')) + float(states('sensor.media_players_active'))|round(0) }}' but no default was specified
```

**Comment by Arroma98** [comment]
Regarding the float(0), you are missing some parentheses.
Correct code:
```
# ALERTS ON sensor
- platform: template
  sensors:
    alerts_on:
      friendly_name: "Alerts on"
      unit_of_measurement: ''
      value_template: "{{ (float(states('sensor.current_lights_on')) + float(states('sensor.locks_unlocked')) + float(states('sensor.media_players_active')))|round(0) }}"
```
